"""Exact-statevector VQE benchmarks for Fermi-Hubbard instances."""

from .hubbard_1x2_hv import (
    DEFAULT_N_LAYERS,
    HALF_FILLING_PARTICLES,
    Hubbard1x2HVVQEProblem,
    apply_hv_ansatz,
    apply_hv_layer,
    basis_indices_with_particle_number,
    build_double_occupancy_projector,
    build_hop_block_unitary,
    build_hopping_generator_term,
    build_hubbard_1x2_hamiltonian,
    build_hv_block_sequence,
    build_hv_layer_unitary,
    build_hv_unit_generators,
    build_onsite_block_unitary,
    build_parametrized_block_unitary,
    build_reference_state_half_filling_noninteracting,
    exact_ground_state,
    exact_ground_state_energy,
    forward_states_hv_ansatz,
    get_generators_hv_1x2,
    get_generators_hv_1x2_5layer,
    parameter_count_hv,
    parameter_metadata_hv_1x2,
    vqe_energy,
    vqe_energy_gradient,
)

__all__ = [
    "DEFAULT_N_LAYERS",
    "HALF_FILLING_PARTICLES",
    "Hubbard1x2HVVQEProblem",
    "apply_hv_ansatz",
    "apply_hv_layer",
    "basis_indices_with_particle_number",
    "build_double_occupancy_projector",
    "build_hop_block_unitary",
    "build_hopping_generator_term",
    "build_hubbard_1x2_hamiltonian",
    "build_hv_block_sequence",
    "build_hv_layer_unitary",
    "build_hv_unit_generators",
    "build_onsite_block_unitary",
    "build_parametrized_block_unitary",
    "build_reference_state_half_filling_noninteracting",
    "exact_ground_state",
    "exact_ground_state_energy",
    "forward_states_hv_ansatz",
    "get_generators_hv_1x2",
    "get_generators_hv_1x2_5layer",
    "parameter_count_hv",
    "parameter_metadata_hv_1x2",
    "vqe_energy",
    "vqe_energy_gradient",
]
